streamlink/streamlink-twitch-gui

package.json
I'm trying to make an Arch package for livestreamer-twitch-gui, and if it installs bower as a dependency, the first time it's run, it asks whether you want to enable analytics, stalling the install. The fix for this is to tell bower not to be interactive.
=> Make bower install non-interactive which was hanging automated install via Arch package

package.json
Updates node-webkit-builder to 1.1.0, adding support for node-webkit url changes
=> Update grunt-node-webkit-builder to 1.0.1

build/resources/linux/add-menuitem.sh
so the script can be ran from any working directory.
=> Make icon paths in add-menuitem.sh absolute

build/resources/windows/msie-minimal.vbs, build/tasks/configs/compile.js, build/tasks/configs/copy.js, package.json, src/app/app.js, src/app/controllers/SettingsController.js, src/app/mixins/ChannelMixin.js, src/app/models/localstorage/Settings.js, src/app/services/ChatService.js, src/app/utils/ParameterCustom.js, src/app/utils/resolvePath.js, src/styles/content/settings.less, src/templates/settings.html.hbs
This enables chat windows without address and bookmarks bars and also adds support for custom chat applications.
Previously, the chat was being opened by calling [`require( "nw.gui" ).Shell.openExternal( url )`](https://github.com/nwjs/nw.js/wiki/Shell#openexternaluri), so it was impossible https://github.com/bastimeyer/livestreamer-twitch-gui/issues/60#issuecomment-80911797 to hide the address and bookmarks bar of the browser window. To be able to do this, the browser executable had to be known, so special launch parameters could be set, but by using `openExternal` there was no way of doing it.
As I've already said here https://github.com/bastimeyer/livestreamer-twitch-gui/issues/9#issuecomment-134084214, I wanted to keep it as simple as possible. The most reasonable solution for me was …
=> Custom chat methods

build/resources/linux/start.sh
See issue #134 
Scope limited to GNOME (although could be broadened).
=> adds application name fix for gnome panel and dock

src/app/components/ApplicationComponent.js
Since OS X per default uses meta instead of ctrl I added this feature to the refresh eventlistener.
=> Added support for OS X-style refresh

CONTRIBUTING.md
Thought it'd be nice to reference the issue template up in the reporting issues section. Also removed an unnecessary 'this' in the pull request section.
=> Reference to issue template and typo fix

package.json
There have been some changes at docs.livestreamer.io, which results in broken links.
=> update livestreamer-docs-url to reflect changes at docs.livestreamer.io

README.md
Homebrew cask doesn't generate a webpage for the package, so best I can do is link to the cask homepage
=> Add homebrew cask to Readme#packages

src/app/config.js, src/app/controllers/SettingsController.js, src/app/initializers/localstorage.js, src/app/models/Livestreamer.js, src/app/models/LivestreamerParameters.js, src/app/models/LivestreamerPlayerParameters.js, src/app/models/localstorage/Settings.js, src/app/services/LivestreamerService.js, src/app/utils/Parameter.js, src/config/players.json, src/styles/routes/Settings.less, src/templates/settings/SettingsPlayer.hbs, src/test/tests/parameters.js
This adds a list of known players and parameters, so that users don't need to specify these by themself and certain player behaviors can be forced. Most of the users will never set player parameters and some will use them incorrectly. Having a list of known parameters and a default configuration for each player will solve multiple issues.
Use these as a fallback and let the user set custom paths.
Player behavior, player window title, buffering/caching, etc.
Tell users about each parameter and give them control over each one.
In addition to (as a replacement of) the enabled parameters.
=> Predefined player parameters

CHANGELOG.md, CONTRIBUTING.md, README.md, build/resources/linux/add-menuitem.sh, build/resources/linux/remove-menuitem.sh, build/resources/linux/start.sh, build/resources/package/chocolatey/livestreamer-twitch-gui.nuspec.tpl, build/resources/package/chocolatey/tools/chocolateyinstall.ps1.tpl, build/resources/package/chocolatey/tools/chocolateyuninstall.ps1.tpl, build/tasks/configs/package.js, build/tasks/configs/template.js, build/travis/templates/releases.md, package.json, src/config/dirs.json, src/config/main.json, src/config/update.json, src/index.html, src/package.json, src/styles/app.less, src/test/package.json
PR for the upcoming repo-rename changes.
I would like to do all this during this weekend if possible.
This will enable the `1.0.0` release.
@cdrage
I'll send you an email (the address on your GH profile) regarding the repo transition, but I also wanted to ping you here, so you can see the status of this PR.
-----
**To the package maintainers:**
I'm pinging you here, because I want to make sure that the transition will be as smooth as possible.
Also, let's ignore the automation part I was talking about in the last release for now... 😃 
@InfernoZeus 
https://github.com/bastimeyer/livestreamer-twitch-gui/commit/94a4a844f52f0877faf02f540ec211e861c1a7af#commitcomment-19451912
The package changes can all easily be done after the `1.0.0` release.
Could you add me to the co-maintainer list then, …
=> Streamlink Twitch GUI

README.md
`streamlink-twitch-gui` can now be found in the stable repository of the Solus Project.
One question though: would you prefer me to replace the link to the source package instead to the link of the binary package? 
i.e. this
https://packages.solus-project.com/shannon/s/streamlink-twitch-gui/
instead of this
https://dev.solus-project.com/source/streamlink-twitch-gui/
Signed-off-by: Joey Riches <josephriches@gmail.com>
=> README: Add Solus to download list

src/config/twitch.json
Twitch recently moved the current chat URL to legacy. Updated the chat URL.
=> Update to non-legacy chat url

src/config/players.json, src/config/streaming.json
add /opt/local/bin path for MacPorts
=> Add more fallback paths for macOS

.github/workflows/check-previous-run.sh, .github/workflows/main.yml, build/tasks/common/platforms.js, build/tasks/configs/aliases.yml, build/tasks/configs/clean.js, build/tasks/configs/run.js, build/tasks/custom/compile.js, build/tasks/custom/dist.js, build/tasks/custom/nwjs.js, build/tasks/custom/release.js, build/tasks/webpack/configurators/dev.js, build/tasks/webpack/configurators/index.js, build/tasks/webpack/configurators/nwjs.js, build/tasks/webpack/configurators/release.js, build/tasks/webpack/configurators/resolve.js, build/tasks/webpack/targets/debug.js, build/tasks/webpack/targets/index.js, build/tasks/webpack/utils.js, src/app/data/models/versioncheck/model.js, src/app/locales/en/modal.yml, src/app/logger.js, src/app/main.js, src/app/nwjs/debug.js, src/app/services/versioncheck.js, src/app/ui/components/modal/modal-debug/component.js, src/app/ui/components/modal/modal-debug/template.hbs, src/config/update.json, src/test/tests/services/versioncheck.js
Resolves #360 
- Renames the old `DEBUG` global var to `DEVELOPMENT`, adds the new `DEBUG` global var, and splits the logic between them accordingly.
- Implements the `build:debug` task alias, which runs tests and creates a debug build via `webpack:debug`.
- Refactors some webpack configs.
- Implements the `:debug` compile flag for the `nwjs`, `compile`, `release` and `dist` tasks.
This flag has to be set at the end of the arguments of each task, eg. `dist:archive_win64:archive_osx64:archive_linux64:debug`.
The debug flag gets passed through to the `nwjs` task, where it will use the NW.js SDK flavor instead of the normal flavor, so that the Chromium dev tools become available in the final debug build.
- Refactors the VersioncheckService.
- Adds a daily warning message when running a debug …
=> Upload scheduled debug builds to Github actions artifacts

build/tasks/webpack/configurators/release.js
In commit 914620a2eaaee619e04cdcb69c84837f59f17814 copy-webpack-plugin
was upgraded from v6.0.3 to v9.0.0, skipping 2 major versions:
-               "copy-webpack-plugin": "6.0.3",
+               "copy-webpack-plugin": "9.0.0",
Unfortunately according to their release notes version 7.0.0 removed the
'transformPath' option used to rename the LICENSE file to LICENSE*.txt*.
This change migrates the build configuration over to using their
templating language instead.
=> build: restore old license txt extension

src/app/locales/it/components.yml, src/app/locales/it/contextmenu.yml, src/app/locales/it/helpers.yml, src/app/locales/it/hotkeys.yml, src/app/locales/it/languages.yml, src/app/locales/it/modal.yml, src/app/locales/it/models.yml, src/app/locales/it/qualities.yml, src/app/locales/it/routes.yml, src/app/locales/it/services.yml, src/app/locales/it/settings.yml, src/app/locales/it/themes.yml, src/config/locales.json
Hi, I tried to translate the software into Italian and the translation of the .yml files is actually complete, but the test build fails here:
```
@ ../test/main.js 24:0-39:2
webpack 5.38.1 compiled with 1 error in 61896 ms
Warning:  Use --force to continue.
Aborted due to warnings.
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
it is my first experience ever and I don't know what the error depends on
I cannot rule out that I have done everything wrong
=> i18n/it: Italian translation

src/app/locales/fr/components.yml, src/app/locales/fr/languages.yml, src/app/locales/fr/modal.yml, src/app/locales/fr/routes.yml, src/app/locales/fr/settings.yml
Hello,
This is an update for the current french translation. Most of it is minor changes (punctuation, 's' added when plural) but I also corrected a few wrong translations (fade out streams for example) and added a few missing strings (--no-keepaspect-window setting, fade and filter in language settings).
Let me know if I need to change some things. The tests run fine, but I had to rebase my commits because I forgot the "i18n/fr" in the commit messages, so hopefully I didn't break stuff :/
=> i18n/fr: Fix some of the french translation

build/resources/appimage/build.sh, build/resources/linux/add-menuitem.sh
In some desktop environments, if someone pins the Appimage version to their panel or dock, they will get a duplicate icon whenever they launch it. 
This is because the launcher icon is associated only with the initial AppRun shell script. When the streamlink-twitch-gui binary is called, a second icon shows up on the user's task-switcher or dock.
Adding this line to the .desktop file prevents this.
=> build: add StartupWMClass to .desktop files

build/tasks/webpack/loaders/parse-json-loader.js, src/app/nwjs/argv.js, src/app/services/hotkey.js, src/app/ui/components/form/text-field/component.js, src/app/utils/linkparser.js, src/app/utils/node/fs/download.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
=> chore: replace String.prototype.substr()

src/app/locales/zh-cn/components.yml, src/app/locales/zh-cn/contextmenu.yml, src/app/locales/zh-cn/helpers.yml, src/app/locales/zh-cn/hotkeys.yml, src/app/locales/zh-cn/languages.yml, src/app/locales/zh-cn/modal.yml, src/app/locales/zh-cn/models.yml, src/app/locales/zh-cn/qualities.yml, src/app/locales/zh-cn/routes.yml, src/app/locales/zh-cn/services.yml, src/app/locales/zh-cn/settings.yml, src/app/locales/zh-cn/themes.yml, src/config/locales.json
Some words are difficult to find appropriate translations for in Chinese, but the ones provided should be enough.
=> i18n/zh-cn: Add Simplified Chinese translation

src/app/ui/components/main-menu/component.js
=> ui/components: fix refresh hotkey binding on macOS
